# Schema for the configuration files of the Currency switcher fixer io module.

currency_switcher_fixer_io.settings:
  type: config_object
  label: 'Currency switcher fixer io settings'
  mapping:
    settings:
      type: mapping
      label: 'Currency switcher fixer io settings'